version: '3.8'
services:
  localdb:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=localdb
    ports:
      - '5432:5432'
    volumes:
      - localdb:/var/lib/postgresql/data
volumes:
  localdb:
    driver: local
